# Generated by Django 5.1.1 on 2024-10-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("gold", "Gold"),
                    ("silver", "Silver"),
                    ("bronze", "Bronze"),
                    ("default", "Default"),
                ],
                default="Default",
                max_length=10,
            ),
        ),
    ]
