# Generated by Django 5.1.1 on 2024-10-14 09:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("gold", "Gold"),
                    ("silver", "Silver"),
                    ("bronze", "Bronze"),
                    ("default", "Default"),
                ],
                default="default",
                max_length=20,
            ),
        ),
    ]
